[[group]]
name = "db_servers"

[[group]]
name = "web_servers"

[[server]]
name = "db1"
ip = "v4:127.0.0.1"
groups = ["db_servers"]

[[server]]
name = "web1"
ip = "v4:127.0.0.2"
groups = ["web_servers"]

[[server]]
name = "web2"
ip = "v4:127.0.0.3"
groups = ["web_servers"]
