[[group]]
name = "all"

[[server]]
name = "testx-1"
ip = "116.202.8.193"
groups = ["all"]

[[server]]
name = "testx-2"
ip = "116.202.13.174"
groups = ["all"]

[[server]]
name = "ubuntu-2gb-fsn1-1"
ip = "78.47.171.55"
groups = ["all"]

[[check]]
from = "all"
to = "all"
check = "udp_ping"