[package]
name = "mehsh_common"
version = "0.1.0"
authors = ["timglabisch <tim@ainfach.de>"]
edition = "2018"

[dependencies]
toml = "0.*"
anyhow = "*"
serde = { version = "1.0", features = ["derive"] }
bytes = "1.4.0"
rand = "*"