[package]
name = "mehsh_check"
version = "0.1.0"
authors = ["timglabisch <tim@ainfach.de>"]
edition = "2018"

[dependencies]
structopt = "0.3.*"
futures = "0.3"
failure = "0.1.*"
bytes = "0.5.3"
rand = "*"
mehsh_common = { path = "../mehsh_common" }

[dependencies.tokio]
version = "0.2"
default-features = true
features = ["full"]
